Vespa-App
ishpaul777/vespa-clone-backend pull request #7
Opened 2022-12-19 09:59 UTC by looh16

**For this project the following functionalities were created:**

1. login endpoint
2. create account endpoint
3. logout endpoint
4. get all products endpoint
5. create products endpoint
6. delete products endpoint
7. create reservations endpoint
8. delete reservations endpoint

[Frontend Link](https://github.com/ishpaul777/vespa-clone-frontend)

2022-12-19 10:58 UTC, Meltrust requested changes
Hi @looh16,

Good job so far!
There are some issues that you still need to work on to prepare your project for the final evaluation, but you are almost there!






### To highlight:

-  Tests are passing✔️
-  API is working well✔️ 
-  Good readme ✔️ 




#### You are really close to finishing the Microverse program!! Keep it up! 👍👍👍

![You can do it](https://media.giphy.com/media/FemTGpEZeK27M5fKL4/giphy.gif)

### After implementing the requested changes, please submit another review request. ♻️
_Check the comments under the review._

_I strongly recommend you take them into account as they can improve your final evaluation._





Cheers and Happy coding!👏👏👏

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the previous reviews unless it is requested otherwise._**

------

2022-12-19 10:58 UTC, Meltrust commented on README.md
> +<a name="readme-top"></a>
- [ ] On your readme, kindly add a "Tests" section with specific instructions about how to run your tests.  That way, your app will be well-documented. 💪 

- [ ] There are two files with tests not yet implemented:

![image](https://user-images.githubusercontent.com/57421823/208405741-67f9006f-a43d-485c-b945-f9861a847b02.png)

These are reservations_helper_spec.rb and reservation_spec.rb.   Kindly either add some tests on those files or remove them.

- [ ]  You are using Rspec, but the "test" folder still exists, which is used by another test framework. Kindly consider deleting that folder if you are not using it. 👍

2022-12-20 19:02 UTC, vichuge reviewed
Hi dear student, 

Great work on making the changes 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![star_wars_almost_there](https://user-images.githubusercontent.com/20563252/121369354-644f4900-c901-11eb-9844-50c85d0f206b.gif)

## Suggested changes
_Check the comments under the review._

## Everything is excellent here (back-end), but there is one bug to fix on the front so, good luck!

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2022-12-20 19:08 UTC, looh16 commented
Thanks!

2022-12-21 08:28 UTC, Meltrust approved these changes
#### Hi @looh16,


# **Wow, you did it 🎉**
![Brilliant](https://media.giphy.com/media/d31w24psGYeekCZy/giphy.gif)
## Thank you for the changes implemented 💪 🥇 ㊗️ 
#### _Unless you want to add more features, go ahead to your final presentation ⏩ ⏩ ⏩_ 
## You are about to finish the Microverse program.  You have come a long way!!!




### Good luck in the software industry!!  I'll see you there. ✨
### **Congratulations!!!!!!**  🎉
![applause](https://media.giphy.com/media/srg19CG0cKMuI/giphy.gif)

### To highlight

- Excellent job ✔️ 




Cheers and Happy coding!👏👏👏


------

2022-12-22 08:50 UTC, merged